### ISSUE TITLE
Add KaTeX support

### ISSUE THREAD

**Issue by ScratchX98** [davidmyersdev/ink-mde#44]
I feel like this would be a really nice feature and I use it daily, at least maybe highlighting $ and $$ signs would be nice.

(This is obv just an enhancement that I would rly appreciate)

**Comment by Karitham** [comment]
@voracious would you be open to see a PR with this? I would greatly enjoy tex support, as I'd like pretty math.

**Comment by voracious** [comment]
Hey @Karitham. I would gladly accept a PR with this feature. 😄
