### ISSUE TITLE
cant install ink-mde when using svelte 4

### ISSUE THREAD

**Issue by demetrius-mp** [davidmyersdev/ink-mde#70]
most likely due to https://github.com/davidmyersdev/ink-mde/blob/f1e8503b7a9d83a42c1bae311a682ec57db17a31/package.json#L124

what do you think of instead of providing a component for the framework (such as svelte or vue), just providing a "copy-pastable" component (since it is very likely that a wrapper will fit in a single component, no matter the framework), which could be shown in the readme, for example? one clear benefit is that version conflicts would never occur.

i believe this is a plausible approach, given that the core of the package itself (i.e. the `ink` export from the package) works in native js.

another approach to avoid version conflicts would be to provide the framework-specific components in a separate package, such as `@ink-mde/svelte` or `@ink-mde/vue`. however, probably not worth the effort

**Comment by demetrius-mp** [comment]
just for the record, the provided component at the `ink-mde/svelte` subpath works fine with svelte 4, so you could simply change the peerDependency to use `"svelte": "^4.0.0"`

**Comment by davidmyersdev** [comment]
Hey @demetrius-mp. If you've confirmed that it works fine with Svelte 4, I can just update the peer dependency to be `^3.0.0 || ^4.0.0` to allow both versions.

**Comment by davidmyersdev** [comment]
Going back to your original point, I do like the idea of a copyable component snippet either way so that people have the option of using either approach.

**Comment by lewisleedev** [comment]
`ink-mde/svelte` works just fine with Svelte4.

**Comment by davidmyersdev** [comment]
I just published [`v0.30.0`](https://github.com/davidmyersdev/ink-mde/releases/tag/v0.30.0) to accept Svelte at `^4.0.0`.
